matrix:
  include:
    - language: node_js
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "TFoQKMBULDkBLHg2DgfhoZw5xosfx8YhXIpuBLFlEu2Nte2tEZR4Ey+/su3fzc3r5ZrJHuncE7fK1z3iHkpxqJ+VmuUwapsOf98Pt7zv5+ukX+/lhxOp6WvocuGjnulAFItYALeEUaMC43oXNVTG/lj+AGfzVXnDjisUK41XN5KToMnSUHkN+ysIkk/NRd8YQ9Bf53kWUc1ZTvbnKwfbKDJ2Xk57tOwv7kiSZ0hMqR5IzMwtD3nFH4W8UyHuNkXsTXmmLEnudlS5/Sxe9ZgdVETKpN/BtFVBbWK68UbHXfAlWLyfpiz6R0oNKGB1a3lGjr3/D+J3YfxuGzSJuWLgci/oMN8D4qskLtPPodyrpo7NzikuqC7DWHTwoLBKAoUMFhiJ2IC5cEvPNK9VsSwIRlOcCELHlwoDRwB6muZe2YUJxPjIb2aWlYdfnqZXJ8hI6dw3LjazhtUf2WAqUlYHhU0ijlHZmMtKY2F8iFSMyJxbMN60Y0ZW9qt7LTKwyBp3zloBBEz9rB29UqLZmvZqs4UW9ILtkKS+s6w4t8FW8R/FfgskE2XyNZfgiaIW52mRlVtAZIixL/13a0cQMyjmb7P1jXDpeEg7mq7VlkHwzNV2KS/4OWCkiaHHtrZaJxmYDGmKnmmDDVozjn3a1S71V81dqWfu6q8q4Lp/jhe5o/A="
      node_js: '12'
      cache:
        - yarn: true
      before_install:
        - cd frontend/caffeine
      install:
        - yarn install
      script:
        #- ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false

    - language: python
      python: '3.7'
      cache:
        - pip: true
      before_install:
        - cd backend/caffeine
      install:
        - pip install -r requirements.txt
      script:
        #- pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ..
        - cd ..
        - sonar-scanner