matrix:
  include:
    - language: node_js
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "sAOoSZYxDtPECH9afwdNK9hTDHSuHpaLPWvLd5p+/RVXKZoBXzyujKo6VnOm3Uemlmh0edL6lbnGfmX9WWJOobaKXSctWC3iYXVZMJjgFA4PpdVbztq0KkqZ1RwXTfvLVHmpVPCvI8Ay8CXlhDyX6lZc805q5T76AEGjPHz4yPIBho83KxM/eLKknefbphvZd5Rbbcji1Z7CwJPk6C4s6zEFRwEjgH1lV3uu/qprisL+uJeGIipSu/Udfh3ynu+RAnp3Tute/Fc8IBvwHh/X2TDQ9kHc6rdPLRwPzbNALiP9VAAlxkVIy13HY2fC8E1rAV1Wgy320e10cg8Of/LZufYmhvpqGS7DjajyNXuYKuNgWj3tg7KAeHM36hcooqnNRzf61ApD3ZkEQrhS2tXx+s3HqZUAmXCxt2dkx9PPSKe8UcpRwtgsfMbXWWoOvq/AMGLWM8pBlJeea5L83EgGq9CBpC0Mi/JgWF+661pUcsNagjyVTyU9rEh58lHtAYGqE9pQTCOlUgOlVN8+XzAwNYrj31SnXvtB1Gi1rj/GCgWYJMB7eSh7f2GAocaW44xTgHlP7VTT3ruxJ8Xp/eXJZJoUZrL7Kexqctk4KO6e5O+k+cwaZy4y43rfNu0xjuU9Hx4tJOZRnN3KKyLjdA2eDNKVeWbSvq7bYhdp7tZGqiQ="
      node_js: '12'
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd ..
        - sonar-scanner

    - language: python
      python: '3.7'
      cache:
        - pip: true
      before_install:
        - cd backend/caffeine
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml