matrix:
  include:
    - language: node_js
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
          secure: "oYNJm9kxRRhPiHjO5cCZHMDTPFRBbA3ThtJ4NQf6HsQlf0nXu+i6o/vZ/aVHgAeLrx1rUwbGzPU94z1tR6A3BihPzWOxnB6+O0zkb/HPwKi6Nt9AZt7/wWv/DT2U9EM17xY5uwYypWO0nVPgolR6CTdrrgNgjkjBQZcmYod1Kb0GaNyAT8yCvbPItgzqdHGYwucNTTkTjYzX8VGts8M4lpdllwKZn8qd299+NYbK5Pp3GlahXBLGcnWizjj3xdWmw97NyBwNWHu/rBKbwwao8AElJJuwQRUEP5FhIR0dYoVwjZZmlKDSo+0gnfswlXJcKP+a9wNazYUwH1c2yC30ZAUzJ0GamHfgMFkZxQtuhyEWbe+SoExPMMqV20JVEmw3xG+b9x/w17+IZpS77nIMLZsPTsVkG1cFdHTCAZemjl55nehnJ3sjNbtHn9fPhhbXPZB48bndtn0o9PUkrJxrct6kX/YGjXbZblj1pnZCHCXyBB+TVW8wUravttfzPfNzCvGoWxC+i4WyPYeEy0lA6/KE0qJtjHSIGCKQoSzMW3QytJtvQD293Ol8LmIFSRLLlfdYVwGpDStUBkhtHV6BgJTFuT+/k7MZJKUr2zTz98dlkjUaUHgNC7oJSE81roiKgJLci+4h45IHvhRWme8WjdokxmeemXr6nwTjSqpAIJE="
      node_js: '12'
      cache:
        - yarn: true
      before_install:
        - cd frontend/caffeine
      install:
        - yarn install
      script:
        - ../node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd ../..
        - sonar-scanner

    - language: python
      python: '3.7'
      cache:
        - pip: true
      before_install:
        - cd backend/caffeine
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml